### PR TITLE
Move dependencies from Gemfile to .gemspec

### PR DESCRIPTION
**Pull request by seethemhigh**
Removes duplication between the files.

### CODE REVIEW

**Comment by ollieglass** [comment]
Great idea, but could you make the changes necessary to fix the Travis CI build?

**Comment by seethemhigh** [comment]
Interesting. I'll try to investigate why it's failing.

**Comment by seethemhigh** [comment]
So looks like the Gemfile.lock can be a major headache when developing gems. According to this post http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/ Gemfile.lock should not be checked into git.

**Comment by ollieglass** [comment]
Nice catch, thank you!

**Pull request merged**
