### PR TITLE
return FB total_count instead of share_count

### PR DESCRIPTION
**Pull request by bricemaurin**
Previous version only returned share_count.

Available counts are:
- share_count
- like_count
- comment_count
- total_count
- commentsbox_count
- comments_fbid
- click_count

I personaly don’t need more than just the total. If you need more, feel
free.

### CODE REVIEW

**Comment by ollieglass** [comment]
This is great, thanks!

I would love to add it, and all of the counts, but returning the share count does fit with this gem's stated purpose: "Returns the number of shares for a link" (from the homepage)

Changing this to the total count wouldn't be consistent with this mission or the other methods.

I am very open to widening the scope of the gem to returning all of these kinds of counts from all networks. But I think the architecture and API calls would need some rethinking, so it's clear what you're getting when you make the call, and the different counts are clearly separated.

What do you think?

**Comment by deuxio** [comment]
well...The *total_count* will return the right value to me:

- Using the current on http://google.com, you'll get [6 944 940 shares](http://sharecounter.deux.io/?url=http://google.com).
- But if you look at what facebook returns as their official 'shares', you'll get [11 981 103 shares](http://graph.facebook.com/http://google.com).

**Comment by ollieglass** [comment]
Sorry I've not replied! Life got in the way.

I'm not clear what all of the different counts are, and which is the best fit with the other networks this gem supports. Do you know of a guide anywhere?

Related, I would love to extend the gem so it returns a default, but makes the other counts available. Any thoughts on that?

**Comment by deuxio** [comment]
Salut Ollie,

If we want to increase the number of sites using the gem, I would suggest being compatible (in term of returns) with https://docs.sharedcount.com/. 

Here is an example:

{"StumbleUpon":30,"Facebook":{"commentsbox_count":18,"click_count":0,"total_count":665170,"comment_count":130249,"like_count":300479,"share_count":234442},"GooglePlusOne":43491,"Twitter":2921,"Pinterest":17,"LinkedIn":1125}

Any thought ?

Brice

**Comment by ollieglass** [comment]
A nested hash, with all of values for each network available - that's perfect. 

Could you possibly add that code?

**Comment by deuxio** [comment]
It won't be possible in may...but I'll add this to my todo ;)

**Comment by ollieglass** [comment]
@deuxio hey this has just been added by @gaganawhad 

Thanks for originally requesting this!

**Pull request closed without merging**
